Many enhancements + support chrome 99
yairp03/SdarotTV-Downloader pull request #3
Opened 2022-03-26 18:24 UTC by Blondy314

2022-03-27 22:55 UTC, yairp03 requested changes
The URL on the download form is a bit useless on its own, I think it should be removed or you can find a way to make it useful.
Besides that, looks great! Can't wait to merge this PR.
Glad you helping me revive this old project ;)

2022-03-27 22:55 UTC, yairp03 commented on src/DownloadForm.Designer.cs
> +            this.txtUrl = new System.Windows.Forms.TextBox();
The URL alone without the cookie is not worth much, I don't know if there's a point in adding it.

2022-04-01 07:16 UTC, Blondy314 commented
Hi,

Removed Download URL and added a few more improvements, hope u like it and
merge :)

Inbar.

On Mon, Mar 28, 2022 at 1:55 AM Yair Peretz ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> The URL on the download form is a bit useless on its own, I think it
> should be removed or you can find a way to make it useful.
> Besides that, looks great! Can't wait to merge this PR.
> Glad you helping me revive this old project ;)
> ------------------------------
>
> In src/DownloadForm.Designer.cs
> <https://github.com/yairp03/SdarotTV-Downloader/pull/3#discussion_r835974132>
> :
>
> > @@ -43,6 +43,7 @@ private void InitializeComponent()
>              this.OverallProgress_Label = new Guna.UI2.WinForms.Guna2HtmlLabel();
>              this.EpisodeLoad_Label = new Guna.UI2.WinForms.Guna2HtmlLabel();
>              this.EpisodeDonwload_Label = new Guna.UI2.WinForms.Guna2HtmlLabel();
> +            this.txtUrl = new System.Windows.Forms.TextBox();
>
> The URL alone without the cookie is not worth much, I don't know if
> there's a point in adding it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yairp03/SdarotTV-Downloader/pull/3#pullrequestreview-922507564>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFHD6FX6Z4DZMVXIFUD7WDDVCDRPTANCNFSM5RXOTYMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-01 07:17 UTC, Blondy314 commented on src/DownloadForm.Designer.cs
> +            this.txtUrl = new System.Windows.Forms.TextBox();
Removed

2022-04-04 17:57 UTC, Blondy314 commented
Any update on merging this?

2022-04-11 11:34 UTC, Blondy314 commented
Hi, pinging on this :)

2022-04-11 11:57 UTC, yairp03 commented
Hi, sorry for the late reply.
I've been busy lately, so I haven't had the chance to review the changes,
hopefully I can do so this week and approve the PR.

On Mon, Apr 11, 2022, 14:34 Blondy314 ***@***.***> wrote:

> Hi, pinging on this :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yairp03/SdarotTV-Downloader/pull/3#issuecomment-1094941653>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK3V2MY6NIDCEOX5Q6RGICLVEQE4TANCNFSM5RXOTYMQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-05-03 15:01 UTC, Blondy314 commented
Pinging again, before they close the site ;)

2022-05-05 15:13 UTC, merged